//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvckutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMİN
    {
        public int Admin_id { get; set; }
        public string KULLANICIADİ { get; set; }
        public string MAIL { get; set; }
        public string SIFRE { get; set; }
    }
}
